services:
  - type: web
    name: telegram-bot-service
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: TELEGRAM_TOKEN
        value: "ضع_توكن_البوت_هنا_بدون_اقتباسات"
      - key: CHAT_ID
        value: "ضع_chat_id_هنا"